### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by kireerik** [sidorares/hot-module-replacement#11]
I got this inconsistent error on start the 3. time:

```bash
node_modules\hot-module-replacement\index.js:24
    function pathsToAcceptingModules(path, root) {
                                    ^

RangeError: Maximum call stack size exceeded
    at pathsToAcceptingModules (node_modules\hot-module-replacement\index.js:24:37)
    at pathsToAcceptingModules (node_modules\hot-module-replacement\index.js:42:9)
    at pathsToAcceptingModules (node_modules\hot-module-replacement\index.js:42:9)
    at pathsToAcceptingModules (node_modules\hot-module-replacement\index.js:42:9)
    at pathsToAcceptingModules (node_modules\hot-module-replacement\index.js:42:9)
    at pathsToAcceptingModules (node_modules\hot-module-replacement\index.js:42:9)
    at pathsToAcceptingModules (node_modules\hot-module-replacement\index.js:42:9)
    at pathsToAcceptingModules (node_modules\hot-module-replacement\index.js:42:9)
    at pathsToAcceptingModules (node_modules\hot-module-replacement\index.js:42:9)
    at pathsToAcceptingModules (node_modules\hot-module-replacement\index.js:42:9)
```

I am getting this in a case as well where I am not actually using this library, but I am requiring like this:
```JavaScript
require('hot-module-replacement')()
```

Version: `3.0.2`
Operating system: `Windows`

**Comment by sidorares** [comment]
can you share modules themselves so I can reproduce locally? Cyclic dependency maybe?
