### ISSUE TITLE
TypeError: Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by ericclemmons** [sidorares/hot-module-replacement#13]
This came up in my fork, but I found that using this project in Next.js, after ~minute of the server running, I'll eventually see this error:

```
.../node_modules/hot-module-replacement/index.js:26
      const requiredMe = parents[root.filename]
                                      ^

TypeError: Cannot read property 'filename' of undefined
    at pathsToAcceptingModules (/Users/eric/Projects/ericclemmons/polydev/node_modules/hot-module-replacement/index.js:26:39)
    at collectDependencies (/Users/eric/Projects/ericclemmons/polydev/node_modules/hot-module-replacement/index.js:46:5)
    at Watcher.<anonymous> (/Users/eric/Projects/ericclemmons/polydev/node_modules/hot-module-replacement/index.js:77:20)
    at Watcher.emit (events.js:182:13)
    at callback (/Users/eric/Projects/ericclemmons/polydev/node_modules/node-watch/lib/watch.js:254:14)
    at /Users/eric/Projects/ericclemmons/polydev/node_modules/node-watch/lib/watch.js:112:10
    at Array.forEach (<anonymous>)
    at Timeout.handle [as _onTimeout] (/Users/eric/Projects/ericclemmons/polydev/node_modules/node-watch/lib/watch.js:107:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

I logged the values right above this:

```js
{ path: [], root: undefined }
```

https://github.com/sidorares/hot-module-replacement/blob/834782b4ee000435c392beb46f34932b0c8c6012/index.js#L24-L25

I wasn't making any changes/saves at the time, so it seems to be a side-effect from the watcher.

**Comment by sidorares** [comment]
interesting. How are you using server-side hmr? Is that for custom next server?

**Comment by ericclemmons** [comment]
Yep, that's correct!
> https://github.com/zeit/next.js/tree/canary/examples/custom-server-express

Our server has Next + GraphQL with shared files (e.g. typeDefs), so `piping` _helps_ (compared to nodemon), but a full restart is very expensive for Next.js.

Webpack's HMR _usually_ works well, but I wanted to avoid webpacking the server (I've done enough of this).

This project works really well, as this was the only edge-case I've come across. 💪

PR incoming...
